-- MAMMUTH•EV | KREATIO UNIVERSAL SYSTEM™ | Code 3620
-- Core Schema — kwf_events e kwf_event_instances

CREATE TABLE kwf_events (
    EVENT_ID TEXT PRIMARY KEY,
    PLACE_ID TEXT NOT NULL,
    NOME_EVENTO TEXT NOT NULL,
    TIPO_PRIMARIO TEXT NOT NULL,
    TIPO_SECONDARIO TEXT,
    MICRO_TERRITORIO TEXT,
    DATA_O_PERIODO TEXT,
    FREQUENZA TEXT,
    CONNESSIONE_LITURGICA TEXT,
    ENTE_ORGANIZZATORE TEXT,
    CONTATTO_O_SITO TEXT,
    ORIGINE_STORICA TEXT,
    ELEMENTO_IDENTITARIO TEXT,
    FONTE TEXT,
    LIVELLO_FONTE TEXT,
    PRIORITA_INTEGRAZIONE TEXT,
    CREATED_AT TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (PLACE_ID) REFERENCES kwf_territory_hub(PLACE_ID)
);

CREATE TABLE kwf_event_instances (
    INSTANCE_ID TEXT PRIMARY KEY,
    EVENT_ID TEXT NOT NULL,
    ANNO INTEGER NOT NULL,
    DATA_INIZIO TEXT,
    DATA_FINE TEXT,
    STATO TEXT DEFAULT 'programmato',
    NOTE TEXT,
    CREATED_AT TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (EVENT_ID) REFERENCES kwf_events(EVENT_ID)
);
